### ISSUE TITLE
user.htm bug

### ISSUE THREAD

**Issue by isSJ** [phith0n/Minos#10]
我发现 user.htm {% if user["username"] != current_user["username"] %}

判断的应该是你访问别人的页面和个人信息的情况，但是判断身份的地方判定的还是自己的power

**Comment by phith0n** [comment]
这里的逻辑是：
当我访问的用户不是我自己的时候（if user["username"] != current_user["username"]），显示该用户的信息
当我访问的用户是我自己的时候，显示self.htm。
应该没有问题吧？
