### ISSUE TITLE
requirements 优化

### ISSUE THREAD

**Issue by vonhng** [phith0n/Minos#17]
我使用python 2.7.14 安装出错如下：
`ERROR: Package 'tornado' requires a different Python: 2.7.14 not in '>= 3.5'`
也就是说 tornado>4.1 需要python>3.6,但是我使用python3.6安装报错如下：
```
Usage: pip [options]

ERROR: Invalid requirement: --allow-external PIL
pip: error: no such option: --allow-external
```
作者是否可以将以来信息写的更全面些，不放尝试下K神的pipenv

**Comment by phith0n** [comment]
感谢关注，不过准备archive这个项目了，代码已经4年没有更新了，使用的python2、tornado等技术栈已过时，现在也有更优秀的项目可以替代。如果后续还想继续使用，可以fork本项目后继续开发。


> 由于技术栈已过时，Minos已弃用，后续不再更新。请使用如下项目进行替换：
> 
> - https://www.youbbs.org/
> - https://bbs.xiuno.com/
> - https://www.discourse.org/
> - https://flarum.org/
