### ISSUE TITLE
ReadMe增加图片

### ISSUE THREAD

**Issue by hustcsxg** [phith0n/Minos#18]
一图抵千文

**Comment by phith0n** [comment]
感谢关注，不过准备archive这个项目了，代码已经4年没有更新了，使用的python2、tornado等技术栈已过时，现在也有更优秀的项目可以替代。如果后续还想继续使用，可以fork本项目后继续开发。

> 由于技术栈已过时，Minos已弃用，后续不再更新。请使用如下项目进行替换：
> 
> - https://www.youbbs.org/
> - https://bbs.xiuno.com/
> - https://www.discourse.org/
> - https://flarum.org/
