### ISSUE TITLE
程序运行后，管理员帐号没有自动创建

### ISSUE THREAD

**Issue by justzx2011** [phith0n/Minos#2]
作者你好，管理员帐号有没有写好的初始化脚本？

**Comment by phith0n** [comment]
哦，这个在TODO LIST里，暂时还没有写~
你可以注册一个账号，并手工在mongodb里将你用户的power设置为20就好了~
`db.member.findAndModify({"username": "your name"}, {"$set": {"power": 20}})`

**Comment by justzx2011** [comment]
新版本mongo这么写好像不好用，我用update方法操作了：db.member.update({"username": "your name"}, {"$set": {"power": 20}})
管理后台貌似还不能手动创建板块？

**Comment by justzx2011** [comment]
sort这个库有没有初始化创建脚本？

**Comment by phith0n** [comment]
哦，我疏忽了，板块添加部分我居然没有加上。
`db.member.insert({"name": "板块名称", "intro":"板块说明","show": True,"article": "该板块文章数目"})`
以上是sort表大致结构，我最近会添加增加板块的部分代码
