### ISSUE TITLE
用户头像上传错误

### ISSUE THREAD

**Issue by justzx2011** [phith0n/Minos#3]
File "/home/work/Minos/controller/user.py", line 43, in detail_act
   "username": {"$eq": username}
    OperationFailure: database error: invalid operator: $eq
[E 150520 07:40:17 web:1825] 500 GET /user/detail (127.0.0.1) 7.15ms

我做了如下修改：

diff --git a/controller/user.py b/controller/user.py
                    "username": {"$eq": username}
                    "username": self.current_user["username"] 

关于find_one函数，mongo中貌似没这个函数，

> db.member.find
> db.member.find(           db.member.findAndModify(  db.member.findOne(

一直不明白这个yield函数参数为什么要这样写？
                user = yield self.db.member.find_one({
                        "username": {"$eq": username}
               })

**Comment by justzx2011** [comment]
类似的写法还有：
150                 if post["charge"]:
151                         charge = int(post["charge"])
152                         old = yield self.db.member.find_and_modify({
153                                 "username": {"$eq": self.current_user["username"]},
154                                 "money": {"$gte": charge}
155                         }, {
156                                 "$inc": {"money": 0 - charge}
157                         })

$gte 与 $eq在程序执行中都会抛出 异常

**Comment by phith0n** [comment]
不应该呀，这是标准的mongodb写法呀？
mongodb里$eq是==，$gte是>=。
$eq可以省略，但$gte不能省略呀，不这么写是肯定不行的。
是不是你的mongodb出BUG了？我这边是好的呀？

关于find_one函数，你直接查看motor的文档：http://motor.readthedocs.org/en/stable/tutorial.html
所有方法都是motor中的。
另外motor是基于pymongo 2.8的，motor文档中没有的方法可以查看pymongo 2.8文档：
http://api.mongodb.org/python/2.8/tutorial.html

**Comment by justzx2011** [comment]
ubuntu15.04执行以下安装操作，可以正确运行：
apt-get install python-dev libjpeg-dev libfreetype6-dev zlib1g-dev libpng12-dev python2.7-dev
apt-get install libcurl4-openssl-dev
cd /usr/include ln -s freetype2 freetype
sudo ln -s /usr/lib/`uname -i`-linux-gnu/libfreetype.so /usr/lib/
sudo ln -s /usr/lib/`uname -i`-linux-gnu/libjpeg.so /usr/lib/
sudo ln -s /usr/lib/`uname -i`-linux-gnu/libz.so /usr/lib/

**Comment by phith0n** [comment]
感谢分享！
