### ISSUE TITLE
最新版本文章查看bug

### ISSUE THREAD

**Issue by justzx2011** [phith0n/Minos#4]
刚刚下载了最新代码，发现文章发布后不论付费还是收费，都需要点击购买，直接导致免费文章无法正常查看

**Comment by phith0n** [comment]
详细说一下？我这边不好复现。
新发布的任何文章都需要付费，还是连以前发布的也需要付费？
主页列表显示的价格是“免费”还是“x金币”？
数据库里article的charge的值都是多少？

**Comment by justzx2011** [comment]
应该还是我本地环境问题，Motor版本是0.4,但是一些方法调用有问题：
    OperationFailure: command SON([('findAndModify', u'member'), ('query', {'username': {'$eq': u'test'}, 'money': {'$gte': 5}}), ('update', {'$inc': {'money': -5}})]) on namespace minos.$cmd failed: exception: invalid operator: $eq

**Comment by justzx2011** [comment]
重新安装环境之后 问题解决了
