### ISSUE TITLE
能否增加金币支付模块？

### ISSUE THREAD

**Issue by justzx2011** [phith0n/Minos#6]
打算用minos做一个付费教学社区，不知道作者能否提供接口支持，支持支付宝即时到帐即可～～～～

**Comment by phith0n** [comment]
我个人实在是没有精力做，抱歉了。支付宝接口应该还是比较好开发的，利用tornado的异步http方法自己写一个难度应该不大。

**Comment by justzx2011** [comment]
使用tornado有一段时间了，一直没搞清楚tornado异步该怎么解释？不知道你是怎么理解的？
